version: "3.9"
services:
  ollama:
    image: ollama/ollama:0.10.0
    container_name: ollama-service
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        ollama serve &
        sleep 5
        ollama pull ${OLLAMA_MODEL:-llama3.2:1b}
        wait
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-24h}
      - OLLAMA_MODEL=llama3.2:1b
    volumes:
      - ollama-storage:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama-storage:
